FORMAT: 1A
HOST: http://localhost/api/v1

# API La'damoda.

# Group Produtos

## Produto Listagem e Criação [/produto]

### Listar Produtos [GET]

+ Response 200 (application/json)
    + Attributes (array[ProdutoCadastrado])

+ Response 404 (application/json)
    + Attributes (Error)

### Cadastrar Produtos [POST]
+ Request Cadastrar produto
    + Headers

            Accept: application/json
            Content-Type: application/json
    + Attributes (ProdutoNovo)

+ Response 201 (application/json)
    + Attributes (Created)

+ Response 400 (application/json)
    + Attributes (Error)

## Produto Apresentação, Atualização e Remoção [/produto/{id}]
+ Parameters
    + id: 1 (number, required) - ID do produto

### Apresentar 1 produto [GET]

+ Response 200 (application/json)
    + Attributes (ProdutoCadastrado)

+ Response 404 (application/json)
    + Attributes (Error)

### Atualizar produto [PUT]

+ Request atualização do produto
    + Headers

            Content-type: application/json
            Accept: application/json
    + Attributes (ProdutoCadastrado)

+ Response 200 (application/json)
    + Attributes (ProdutoCadastrado)

+ Response 404 (application/json)
    + Attributes (Error)

### Deletar Produto [DELETE]
+ Response 204 (application/json)

+ Response 404 (application/json)
    + Attributes (Error)

## Busca de produto por parametros de código/sku/descricao [/produto/{parameter}/{value}]
+ Parameters
    + parameter: code (string, required) - Atributo a ser pesquisado.
    + value: 123564a (string, required) - Valor para filtro do produto.
### Seach Produto [GET]

+ Response 200 (application/json)
    + Attributes (ProdutoCadastrado)

+ Response 404 (application/json)
    + Attributes (Error)



# Group Pedidos de Compra

**O Atributo (delete) no item de pedido de compra, deverá existir somente  se um item de compra for excluído na ação de atualização.**

## EndPoint Pedidos de compras: Criação e listagem [/pedido-compra]

### Criar pedido de compra [POST]

+ Request criar pedido de compra

    + Headers
            
            Accept: application/json
            Content-Type: application/json
    + Attributes (PedidoCompraNovo)

+ Response 201 (application/json)
    + Attributes (Created)

+ Response 400 (application/json)
    + Attributes (Error)

### Lista de pedidos de compra [GET]

+ Response 200 (application/json)
    + Attributes (array[PedidoCompraCadastrado])

+ Response 400 (application/json)
    + Attributes (Error)

## Pedido de compra Apresentação, Atualização e remoção [/pedido-compra/{id}]
+ Parameters
    + id: 1 (number, required) - Id do pedido de compra

### Apresentação do pedido de compra [GET]
+ Response 200 (application/json)
    + Attributes (PedidoCompraCadastrado)
    
+ Response 404 (application)
    + Attributes (Error)

### Atualização do Pedido de Compra [PUT]
+ Request dados do pedido a serem atualizados
    
    + Headers

            Content-type: application/json
            Accept: application/json
    + Attributes (PedidoCompraCadastrado)
    
+ Response 200 (application/json)
    + Attributes (PedidoCompraCadastrado)

+ Response 400 (application/json)
    + Attributes (Error)

### Remoção do pedido de compra [DELETE]
+ Response 204 (application/json)

+ Response 400 (application/json)
    + Attributes (Error)

## Filtros para pedidos de compras [/pedido-compra/filtro]

### Request Dados opcionais para listar pedidos de compra [POST]
+ Request 
    + Headers

            Accept: application/json
            Content-Type: application/json
    + Attributes (FiltroPedidoCompra)

+ Response 200 (application/json)
    + Attributes (array[PedidoCompraCadastrado])

+ Response 400 (application/json)
    + Attributes (Error)

# Group Modalidade de Produto

## EndPoint Modalidade [/modalidade]

### Criar Modalidade [POST]

+ Request criar modalidade para produtos
    + Header

            Accept: (application/json)
            Content-Type: (application/json)
    + Attributes (ModalidadeNova)

+ Response 201 (application/json)
    + Attributes (Created)

+ Response 400 (application/json)
    + Attributes (Error)

### Listar Modalidadde [GET]

+ Response 200 (application/json)
    + Attributes (array[ModalidadeCadastrada])

+ Response 404 (application/json)
    + Attributes (Error)

# Group Categoria de produtos

## EndPoint para categorias de produtos [/categoria]

### Listar categoria de produtos [GET]
+ Response 200 (application/json)
    + Attributes (array[CategoriaCadastrada])

+ Response 404 (application/json)
    + Attributes (Error)

### Cadastrar categoria de produtos [POST]
+ Request Cadastrar categoria de produtos
    + Headers

            Accept: application/json
            Content-type: application/json
    + Attributes (CategoriaNova)

+ Response 201 (application/json)
    + Attributes (Created)

+ Response 400 (application/json)
    + Attributes (Error)

# Group Fornecedor

## EnPoint para apresentar e gravar fornecedor [/fornecedor]

### Listar fornecedor [GET]

+ Response 200 (application/json)
    + Attributes (array[FornecedorCadastrado])

+ Response 404 (application/json)
    + Attributes(Error)

### Cadastrar fornecedor [POST]
+ Request Cadastrar fornecedores
    + Headers

            Accept: application/json
            Content-Type: application/json
    + Attributes (FornecedorNovo)

+ Response 201 (application/json)
    + Attributes (Created)

+ Response 400 (application/json)
    + Attributes (Error)

## Endpoints para apresentação, atulaização e remoção de fornecedor [/fornecedor/{id}]

+ Parameters
    + id: 1 (number, required) - id do fornecedor
### Apresenta fornecedor [GET]

+ Response 200 (application/json)
    + Attributes (FornecedorCadastrado)
+ Response 404 (application/json)
    + Attributes (Error)

### Atualizar fornecedor [PUT]
+ Request atualizar fornecedor
    + Headers

            Content-Type: application/json
            Accept: application/json

    + Attributes (FornecedorCadastrado)

+ Response 200 (application/json)
    + Attributes (FornecedorCadastrado)

+ Response 400 (application/json)
    + Attributes (Error)

### Remover fornecedor [DELETE]
+ Response 204 (application/json)

+ Response 404 (application/json)
    + Attributes (Error)

# Group Tamanhos

## EndPoint Tamanhos para Produto [/tamanho]

### Criar tamanho para produto [POST]

+ Request criar tamanho para produto

    + Headers

            Accept: application/json
            Content-Type: application/json
    + Attributes (TamanhoNovo)

+ Response 201 (application/json)
    + Attributes (Created)

+ Response 400 (application/json)
    + Attributes (Error)

### Listar Tamanho [GET]
+ Response 200 (application/json)
    + Attributes (array[TamanhoCadastrado])

+ Response 400 (application/json)
    + Attributes (Error)

# Group Cores

## EndPoint Cores de produtos [/cor]

### Listar Cores [GET]
+ Response 200 (application/json)
    + Attributes (array[CorCadastrada])

+ Response 400 (application/json)
    + Attributes (Error)

### Cadastrar Cor [POST]

+ Request criar cores para produtos

    + Headers

            Content-type: application/json
            Accept: application/json
    + Attributes (CorNova)

+ Response 201 (application/json)
    + Attributes (Created)

+ Response 400 (application/json)
    + Attributes (Error)

# Group Estampas

## EndPoint Estampas de produtos [/estampa]

### Listar estampas [GET]
+ Response 200 (application/json)
    + Attributes (array[EstampaCadastrada])

+ Response 400 (application/json)
    + Attributes (Error)

### Cadastrar Estampa [POST]

+ Request criar estampa para produtos

    + Headers

            Content-type: application/json
            Accept: application/json
    + Attributes (EstampaNova)

+ Response 201 (application/json)
    + Attributes (Created)

+ Response 400 (application/json)
    + Attributes (Error)
# Group Grade

## Endpoint de lista de cadastro de grade [/grade]

### Listar grade de produtos [GET]
+ Response 200 (application/json)
    + Attributes (array[GradeCadastrada])

+ Response 400 (application/json)
    + Attributes (Error)

### Cadastro de grade [POST]
+ Request 

    + Headers

            Accept: application/json
            Content-Type: application/json
    + Attributes (GradeNova)

+ Response 201 (application/json)
    + Attributes (Created)

+ Response 400 (application/jsosn)
    + Attributes (Error)


# Data Structures

## ProdutoNovo 
+ code: 123564 (string)
+ code_sku: LA123564 (string)
+ name: Blusa de alsa (string)
+ composition: 84% POLIAMIDA 16% ELASTANO FORRO 100% ALGODÃO (string)
+ cost_value: 25.60 (number)
+ category (CategoriaCadastrada)
+ modality (ModalidadeCadastrada)
+ vendor (FornecedorCadastrado)
+ grade (array[GradeCadastrada])
+ sale_value: 57.00 (number) 
+ profit_porcentagem: 30 (number) 
+ start_date: `2021-09-24` (string) - Data do Produto
+ ncm: 123245 (number)

## ProdutoCadastrado (ProdutoNovo)
+ id: 1 (number)

## GradeNova
+ size (TamanhoCadastrado)
+ print (EstampaCadastrada)
+ color (CorCadastrada)

## GradeCadastrada (GradeNova)
+ id: 1 (number)

## PedidoCompraItemCadastrado (PedidoCompraItemNovo)
+ delete: 1 (number) - Opcional, em caso de atualização de pedido e um produto fou exluído
+ order_purchase_id: 1 (number)

## PedidoCompraItemNovo
+ quantity: 3 (number)
+ product (ProdutoCadastrado)
+ grade (GradeCadastrada)

## ProdutoPurchase
+ id: 1 (number)
+ code: 123454 (number)
+ name: Blusa de alsa (string)
+ cost_value: 25.60
+ modality (ModalidadeCadastrada)


## PedidoCompraCadastrado (object)
+ id: 1 (number)
+ vendor (FornecedorCadastrado)
+ items_purchase (array[PedidoCompraItemCadastrado])
+ purchase_number: PR0000007 (string)
+ date: `2021-09-17` (string)
+ purchase_value: 467.99 (number) 

## PedidoCompraNovo (object)
+ vendor (FornecedorCadastrado)
+ items_purchase (array[PedidoCompraItemNovo])
+ purchase_number: PR0000007 (string)
+ date: `2021-09-17` (string)

## FiltroPedidoCompra (object)
+ purchase_number: PR0000007 (string)
+ date_start: `2021-05-01` (string)
+ date_end: `2021-07-01` (string)
+ category: 1 (number)

## FornecedorNovo (object)
+ name: Loja do Brás (string)
+ email: loja@bras.com.br (string)
+ telephone: 11989765412 (number)
+ cnpj: 042598880001 (number)

## FornecedorCadastrado (FornecedorNovo)
+ id: 1 (number)

## TamanhoNovo (object)
+ name: M (string)
## TamanhoCadastrado (TamanhoNovo)
+ id: 1 (number)

## CorNova (object)
+ name: Azul (string)

## CorCadastrada (CorNova)
+ id: 1 (number)

## EstampaNova (object)
+ name: Lisa (string)

## EstampaCadastrada (EstampaNova)
+ id: 1 (number)

## ModalidadeNova (object)
+ name: Revenda (string)

## ModalidadeCadastrada (ModalidadeNova)
+ id: 1 (number)

## CategoriaNova (object)
+ name: Camisas Femininas (string)
## CategoriaCadastrada (CategoriaNova)
+ id: 1 (number)

## Created (object)
+ id: 1 (number) - Id do Pedido de Compra

## Error (object)
+ code: 400 (number)
+ message: Mensagem do erro
+ description: descrição do status

